### ISSUE TITLE
No module named 'jat.eval'

### ISSUE THREAD

**Issue by HArars** [huggingface/jat#167]
> python scripts/eval_jat.py --model_name_or_path jat-project/jat --tasks atari-pong --trust_remote_code
pygame 2.5.2 (SDL 2.28.3, Python 3.10.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "\Packets\Projects\Gits\jat\scripts\eval_jat.py", line 16, in <module>
    from jat.eval.rl import TASK_NAME_TO_ENV_ID, make
ModuleNotFoundError: No module named 'jat.eval'

**Comment by qgallouedec** [comment]
Hey, thanks for reporting. Can you confirm that you've installed jat? (`pip show jat`)

**Comment by HArars** [comment]
I can only use "from jat.eval.rl import make" in the jat folder. 
----------------
Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from jat.eval.rl import make
pygame 2.5.2 (SDL 2.28.3, Python 3.10.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>>

**Comment by HArars** [comment]
```shell 
(jat) PS D:\Packets\Projects\Gits\jat> python
Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from jat.eval.rl import make
pygame 2.5.2 (SDL 2.28.3, Python 3.10.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> exit()
(jat) PS D:\Packets\Projects\Gits\jat> cd ..
(jat) PS D:\Packets\Projects\Gits> python
Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from jat.eval.rl import make
pygame 2.5.2 (SDL 2.28.3, Python 3.10.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jat.eval' !!Here
>>>
```

**Comment by HArars** [comment]
@qgallouedec  Under the 'jat/eval' folder, the '__init__.py' file is missing.

**Comment by qgallouedec** [comment]
Good catch! thanks
