### ISSUE TITLE
How many tokens are in dataset in total?

### ISSUE THREAD

**Issue by suessmann** [huggingface/jat#169]
First of all, thanks for the great work! I believe that the future of decision-making AI is hugely dependent on the open source, so you are truly doing an important job.

So, to the question itself: could you please provide at least approximate number of tokens in JAT dataset? It is hard for us to calculate it directly, since the data size is ~1TB.

Thanks!

**Comment by qgallouedec** [comment]
```python
from datasets import load_dataset, get_dataset_config_names

for split in ["train", "test"]:
    for config in get_dataset_config_names("jat-project/jat-dataset"):
        dataset = load_dataset("jat-project/jat-dataset", config, split=split, streaming=True)
        num_tokens = 0
        for episode in dataset:
            num_tokens += 3*len(episode["rewards"]) # 3 because each interraction has observation, action and reward
        print(f"| {config} | {num_tokens} |")
```

it's running, I'll edit this comment when it's done :)

**Comment by suessmann** [comment]
merci beaucoup!
