### ISSUE TITLE
Issues with Training JAT

### ISSUE THREAD

**Issue by kaustubhsridhar** [huggingface/jat#170]
Hi,
First of all, I am really thankful for this great work collecting many of the Gato datasets and providing a great codebase to start on. But, I've run across some basic errors where I'm hoping to get some clarification or help.

* There is no function called `mix_iterable_datasets` in jat.utils but it is still imported in `scripts/train_jat.py`. This prevents me from running `scripts/train_jat.py`.
* The command to train jat in the README has a few problems:

(a) It uses `scripts/train_jat_tokenized.py` even though the tokenized dataset was [originally said to be unavailable](https://x.com/QGallouedec/status/1785240738432798930) but now is seemingly available at [this link](https://huggingface.co/datasets/jat-project/jat-dataset-tokenized)? It would be great to get a clarification on what the tokenized dataset is and if that is recommended for use. For now, it seems like the tokenized dataset is a superset of the raw dataset and was updated last in Dec 2023 (which is much before the raw dataset).

(b) While trying to run `scripts/train_jat_tokenized.py` anyway with the command in the readme, it seems to look for the `jat-project/jat-small` on huggingface which seems to be private. Is there a clean command to train the model from scratch?

**Comment by qgallouedec** [comment]
Hey thanks for your questions_

> * There is no function called `mix_iterable_datasets` in jat.utils but it is still imported in `scripts/train_jat.py`. This prevents me from running `scripts/train_jat.py`.

Indeed, fixed in #171

> * The command to train jat in the README has a few problems:
> 
> (a) It uses `scripts/train_jat_tokenized.py` even though the tokenized dataset was [originally said to be unavailable](https://x.com/QGallouedec/status/1785240738432798930) but now is seemingly available at [this link](https://huggingface.co/datasets/jat-project/jat-dataset-tokenized)? It would be great to get a clarification on what the tokenized dataset is and if that is recommended for use. For now, it seems like the tokenized dataset is a superset of the raw dataset and was updated last in Dec 2023 (which is much before the raw dataset).


Sorry if it seems unclear, but we changed our minds along the way.

This part of the code, corresponding to preprocessing, takes a long time to run. So we decided to preprocess the dataset once and for all to avoid having to do it again for each training session.

https://github.com/huggingface/jat/blob/912dc9c8d5a46390227f876a4072813310bd8f0e/scripts/train_jat.py#L145-L179

Unless you change the preprocessing, we recommend using `train_jat_tokenized.py`, which will use the preprocessed dataset directly.

> (b) While trying to run `scripts/train_jat_tokenized.py` anyway with the command in the readme, it seems to look for the `jat-project/jat-small` on huggingface which seems to be private. Is there a clean command to train the model from scratch?


`jat-small` has been renamed `jat` as we only release one size. I've changed the command in #171 as well

**Comment by kaustubhsridhar** [comment]
Thank you very much @qgallouedec :)

About the tokenized dataset: it seems to contain many more rows per task than the raw dataset for Atari. Here is a screenshot from the viewer of the raw dataset.

![image](https://github.com/huggingface/jat/assets/24416829/fab294bb-bb78-4d14-bf54-44d9d8e1885b)

And here is a screenshot from the tokenized dataset.

![image](https://github.com/huggingface/jat/assets/24416829/2a7519a8-cfe4-4afe-82ec-0781537caa89)

The tokenized dataset has two orders of magnitude more rows (episodes I believe) than the raw dataset.

This appears to be true for mujoco as well. The raw dataset:
![image](https://github.com/huggingface/jat/assets/24416829/29222b50-3395-4f0a-81ac-5b17d4d1b93a)


The tokenized dataset:
![image](https://github.com/huggingface/jat/assets/24416829/a338c37e-bee4-426c-a475-2e3ac16fe268)

Why is there such a large difference?

**Comment by qgallouedec** [comment]
Yes it is expected. Episodes may be longer than the model max input length. When it's the case, instead of truncating and discard the end of the episode, we reuse it to create a new sample. Eg:

Before processing
```
Row 1: A B C D E F G H I J K
Row 2: L M N O P Q R S
```

After processing (with max length of 4, padding value is `0`)
Before processing
```
Row 1: A B C D
Row 2: E F G H
Row 3: I J K 0
Row 4: L M N O
Row 5: P Q R S
```

**Comment by kaustubhsridhar** [comment]
I see. Thank you very much. That makes sense. Is there any indicator of which rows belong to the same episode in the tokenized dataset? If I need that information, should I just compute it with raw episode lengths and max_length of 20?
